spring.application.name=gym-app
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.profiles.active=local

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Gym Application
info.app.description=Gym management REST API
